version: '3.9'
services:
  es:
    image: elasticsearch:8.12.0
    container_name: es
    privileged: true
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./data:/usr/share/elasticsearch/data"
      - "./plugins:/usr/share/elasticsearch/plugins"
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./logs:/usr/share/elasticsearch/logs"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      TZ: "Asia/Shanghai"
      LANG: "en_US.UTF-8"
      ELASTIC_PASSWORD: "123456"
    networks:
      - es-net

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    privileged: true
    restart: unless-stopped
    ports:
      - "5601:5601"
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    depends_on:
      - es
    links:
      - es
    networks:
      - es-net

networks:
  es-net:
    driver: bridge